function cost = cost_energy(x, u, d,du,params)
    persistent Ch S R0 C0 gamma 
    global PathToParameters
    if isempty(Ch) || isempty(S) || isempty(R0) || isempty(C0) || isempty(gamma)
        load(PathToParameters ,'Ch', 'S', 'R0','C0','gamma');
    end
     cost =      1e-6*(Ch*x(1).^2)       *params(1)...
                +1e-6*x(3:5)'*S*x(3:5)   *params(2)...
                +u/R0                    *params(3)...
                +1e-6*x(1)*d             *params(4)...
                +0.5*C0*du               *params(5)...
                +0.5*gamma*x(2).^2*du    *params(6)...
                +2*gamma*x(1)*x(2)*u     *params(7);


end

